//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlımSatımGecmisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlımSatımGecmisi()
        {
            this.Odeme = new HashSet<Odeme>();
        }
    
        public System.DateTime Tarih { get; set; }
        public Nullable<int> ParaID { get; set; }
        public Nullable<decimal> KullanilanTutar { get; set; }
        public int KullanıcıID { get; set; }
        public Nullable<int> YöneticiID { get; set; }
    
        public virtual AlımSatımGecmisi AlımSatımGecmisi1 { get; set; }
        public virtual AlımSatımGecmisi AlımSatımGecmisi2 { get; set; }
        public virtual KullanıcıKayıt KullanıcıKayıt { get; set; }
        public virtual ParaTürleri ParaTürleri { get; set; }
        public virtual YöneticiKayıt YöneticiKayıt { get; set; }
        public virtual AlımSatımGecmisi AlımSatımGecmisi11 { get; set; }
        public virtual AlımSatımGecmisi AlımSatımGecmisi3 { get; set; }
        public virtual AlımSatımGecmisi AlımSatımGecmisi12 { get; set; }
        public virtual AlımSatımGecmisi AlımSatımGecmisi4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odeme> Odeme { get; set; }
    }
}
