//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YöneticiKayıt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YöneticiKayıt()
        {
            this.AlımSatımGecmisi = new HashSet<AlımSatımGecmisi>();
            this.BakiyeBilgi = new HashSet<BakiyeBilgi>();
            this.BakiyeBilgi1 = new HashSet<BakiyeBilgi>();
        }
    
        public int YöneticiID { get; set; }
        public string YoneticiAd { get; set; }
        public string YoneticiSoyad { get; set; }
        public string Eposta { get; set; }
        public Nullable<int> YöneticiTcNo { get; set; }
        public Nullable<int> Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlımSatımGecmisi> AlımSatımGecmisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BakiyeBilgi> BakiyeBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BakiyeBilgi> BakiyeBilgi1 { get; set; }
        public virtual YöneticiKayıt YöneticiKayıt1 { get; set; }
        public virtual YöneticiKayıt YöneticiKayıt2 { get; set; }
    }
}
